version: 2

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

# formats:
#    - pdf
#    - epub

# python:
#   install:
#     - requirements: docs/requirements.txt